server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: sr-vecinet-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

ms-vecinet:
  auth:
    url: ${MS_VECINET_AUTH_URL}
    context-path: ms-vecinet-auth
  post:
    url: ${MS_VECINET_POST_URL}
    context-path: ms-vecinet-post


loggin.level.root: info
loggin.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Configuracion de jtw secret
jwt:
  secret: ${JWT_SECRET}